[config.custom_colors]

[templates.kde]
input_path = "templates/BreezeDark.colors"
mode = "Dark"
output_path = "~/.config/kdeglobals"
# post_hook = "systemctl restart --user plasma-xdg-desktop-portal-kde.service"

[templates.nvim]
input_path = "templates/nvim.json"
mode = "Dark"
output_path = "~/.local/share/nvim-colors.json"

[templates.qt5ct]
input_path = "templates/qtct-colors.conf"
mode = "Dark"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.qt6ct]
input_path = "templates/BreezeDark.colors"
mode = "Dark"
output_path = "~/.config/qt6ct/colors/BreezeDark.colors"

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.foot]
input_path = 'templates/foot.ini'
output_path = '~/.config/foot/foot.ini'
